title: PSU Computer Science Guide
description: A four-year Penn State Computer Science guide on classes and the job application process.
theme: just-the-docs

url: https://cdarlington-dev.github.io/psu-cs-guide/

